FROM <REPLACE_WITH_YOUR_CONTAINER_URI>

RUN pip3 install git+https://github.com/huggingface/transformers

ENV SAGEMAKER_SUBMIT_DIRECTORY /opt/ml/code
ENV SAGEMAKER_PROGRAM train.py

COPY 1_sources/train.py  $SAGEMAKER_SUBMIT_DIRECTORY/$SAGEMAKER_PROGRAM

